export { default as Header } from './Header'
export { default as Main } from './Main'
export { default as LinksHome } from './LinksHome'
export { default as ContactForm } from './ContactForm'
export { default as Footer } from './Footer'